"use strict";

import mongoose from "mongoose";
const { Schema } = mongoose;

// Definición del esquema para el modelo de Usuario
const UsuarioSchema = new Schema(
  {
    cedula: {
      type: String,
      required: true,
      unique: true,
      description: "Identification number",
    },
    nombres: { type: String, required: true, description: "Full name" },
    telefono: { type: String, required: true, description: "Phone number" },
    rol_user: {
      type: Schema.Types.ObjectId,
      ref: "rol_user" || "role",
      required: true,
      description: "User role",
    },
    correo: {
      type: String,
      required: true,
      unique: true,
      description: "Email address",
    },
    password: { type: String, required: true, description: "Password" },
    foto: { type: String, description: "Profile picture" },
    estado: { type: String, default: "On", description: "User account status" },
  },
  {
    timestamps: true,
  }
);
UsuarioSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
UsuarioSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de Rol_user
const RolUserSchema = new Schema(
  {
    nombre: { type: String, description: "Role name" },
    orden: { type: Number, unique: true, description: "Role order" },
  },
  {
    timestamps: true,
  }
);
RolUserSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
RolUserSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de Ficha_sectorial
//categoria: { type: Schema.Types.ObjectId, ref: 'categoria', required: true },
// Definición del esquema para el modelo de Ficha_sectorial
const FichaSectorialSchema = new Schema(
  {
    descripcion: { type: String, required: true, description: "Description" },
    encargado: {
      type: Schema.Types.ObjectId,
      ref: "user",
      required: true,
      description: "Responsible user",
    },
    direccion_geo: {
      nombre: { type: String, required: true, description: "Location name" },
      latitud: { type: Number, required: true, description: "Latitude" },
      longitud: { type: Number, required: true, description: "Longitude" },
    },
    estado: {
      type: Schema.Types.ObjectId,
      ref: "estado_actividad_proyecto",
      description: "Project activity status",
      required: true,
    },
    actividad: {
      type: Schema.Types.ObjectId,
      ref: "actividad_proyecto",
      description: "Project activity",
    },
    fecha_evento: { type: Date, description: "Event date" },
    observacion: { type: String, description: "Observation" },
    foto: [{ type: String, description: "Photos" }],
    view: { type: Boolean, default: true, description: "View status" },
    view_id: {
      type: Schema.Types.ObjectId,
      ref: "user",
      description: "Viewed by",
    },
    view_date: { type: Date, default: Date.now, description: "View date" },
    // Nuevos campos para artículos y marcadores en mapa
    destacado: {
      type: Boolean,
      default: false,
      description: "Fichas en Home",
    },
    es_articulo: {
      type: Boolean,
      default: false,
      description: "Is an article",
    },
    mostrar_en_mapa: {
      type: Boolean,
      default: false,
      description: "Show on map",
    },
    title_marcador: {
      type: String,
      description: "Show on map",
    },
    icono_marcador: {
      type: String,
      default: "https://i.postimg.cc/J7XxJ9b9/esme-2.png",
      description: "Marker icon",
    },
    // Campos para compartir, me gusta y comentarios
    compartido: {
      type: Number,
      default: 0,
      description: "Number of times shared",
    },
    me_gusta: [
      {
        type: Schema.Types.ObjectId,
        ref: "user",
        description: "Users who liked",
      },
    ],
    comentarios: [
      {
        usuario: {
          type: Schema.Types.ObjectId,
          ref: "user",
          required: true,
          description: "User who commented",
        },
        contenido: {
          type: String,
          required: true,
          description: "Comment content",
        },
        fecha_comentario: {
          type: Date,
          default: Date.now,
          description: "Comment date",
        },
      },
    ],
  },
  {
    timestamps: true,
  }
);

FichaSectorialSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
FichaSectorialSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};

// Definición del esquema para el modelo de Incidentes_denuncia
const IncidentesDenunciaSchema = new Schema(
  {
    categoria: {
      type: Schema.Types.ObjectId,
      ref: "categoria",
      required: true,
      description: "Category",
    },
    subcategoria: {
      type: Schema.Types.ObjectId,
      ref: "subcategoria",
      required: true,
      description: "Subcategory",
    },
    direccion_geo: {
      nombre: { type: String, required: true, description: "Location name" },
      latitud: { type: Number, required: true, description: "Latitude" },
      longitud: { type: Number, required: true, description: "Longitude" },
    },
    ciudadano: {
      type: Schema.Types.ObjectId,
      ref: "user",
      required: true,
      description: "Citizen reporting the incident",
    },
    estado: {
      type: Schema.Types.ObjectId,
      ref: "estado_incidente",
      description: "Incident status",
      required: true,
    },
    foto: [{ type: String, description: "Photos" }],
    descripcion: { type: String, required: true, description: "Description" },
    encargado: {
      type: Schema.Types.ObjectId,
      ref: "user",
      description: "Responsible user",
    },
    respuesta: { type: String, description: "Response" },
    evidencia: [{ type: String, description: "Evidence" }],
    view: { type: Boolean, default: true, description: "View status" },
    view_id: {
      type: Schema.Types.ObjectId,
      ref: "user",
      description: "Viewed by",
    },
    view_date: { type: Date, default: Date.now, description: "View date" },
  },
  {
    timestamps: true,
  }
);
IncidentesDenunciaSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
IncidentesDenunciaSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de Categoria
const CategoriaSchema = new Schema(
  {
    nombre: { type: String, required: true, description: "Category name" },
    descripcion: {
      type: String,
      required: true,
      description: "Category description",
    },
    icono: { type: String, description: "Icon" },
  },
  {
    timestamps: true,
  }
);
CategoriaSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
CategoriaSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de Subcategoria
const SubcategoriaSchema = new Schema(
  {
    categoria: {
      type: Schema.Types.ObjectId,
      ref: "categoria",
      require: true,
      description: "Category",
    },
    nombre: { type: String, require: true, description: "Subcategory name" },
    descripcion: {
      type: String,
      require: true,
      description: "Subcategory description",
    },
    icono: { type: String, description: "Icon" },
  },
  {
    timestamps: true,
  }
);
SubcategoriaSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
SubcategoriaSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de Encargado_categoria
const EncargadoCategoriaSchema = new Schema(
  {
    encargado: [{ type: Schema.Types.ObjectId, ref: "user" }],
    categoria: { type: Schema.Types.ObjectId, ref: "categoria", require: true },
  },
  {
    timestamps: true,
  }
);
EncargadoCategoriaSchema.statics.isProtected = function (method) {
  const protectedMethods = ["get", "post", "put", "delete"];
  return protectedMethods.includes(method);
};
EncargadoCategoriaSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de Estado_incidente
const EstadoIncidenteSchema = new Schema(
  {
    nombre: {
      type: String,
      unique: true,
      description: "Incidente status name",
    },
    orden: { type: Number, required: true, description: "Orden" },
  },
  {
    timestamps: true,
  }
);
EstadoIncidenteSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
EstadoIncidenteSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de Estado_actividad_proyecto
const EstadoActividadProyectoSchema = new Schema(
  {
    nombre: { type: String, unique: true, description: "Activity status name" },
    orden: { type: Number, required: false, description: "Order" },
  },
  {
    timestamps: true,
  }
);
EstadoActividadProyectoSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
EstadoActividadProyectoSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de Actividad_proyecto
const ActividadProyectoSchema = new Schema(
  {
    nombre: { type: String, description: "Activity name" },
    icono: { type: String, description: "Icon" },
  },
  {
    timestamps: true,
  }
);
ActividadProyectoSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
ActividadProyectoSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de Direccion_geo
const DireccionGeoSchema = new Schema(
  {
    nombre: { type: String, description: "Location name" },
    latitud: { type: Number, description: "Latitude" },
    longitud: { type: Number, description: "Longitude" },
  },
  {
    timestamps: true,
  }
);
DireccionGeoSchema.statics.isProtected = function (method) {
  const protectedMethods = ["get", "post", "put", "delete"];
  return protectedMethods.includes(method);
};
DireccionGeoSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Definición del esquema para el modelo de permisos
// Definición del esquema para el modelo de permisos
const permisosSchema = new Schema(
  {
    nombreComponente: {
      type: String,
      required: true,
      description: "Component name",
    },
    rolesPermitidos: [
      {
        type: Schema.Types.ObjectId,
        ref: "rol_user" || "role",
        required: true,
        description: "Allowed roles",
      },
    ],
  },
  {
    timestamps: true,
  }
);
permisosSchema.statics.isProtected = function (method) {
  const protectedMethods = ["get", "post", "put", "delete"];
  return protectedMethods.includes(method);
};
permisosSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};

const RecolectoresSchema = new Schema(
  {
    dateOnly: { type: String },
    deviceId: {
      type: String,
      required: true,
      description: "Collector ID API EXTERNAL",
    },
    funcionario: {
      type: Schema.Types.ObjectId,
      ref: "user",
      required: false,
      description: "Funcionario a cargo del vehículo",
    },
    externo: {
      type: Schema.Types.ObjectId,
      ref: "externo", // Referencia al esquema Externo
      required: false,
    },
    ruta: [
      {
        id: {
          type: Number,
          required: true,
        },
        attributes: {
          distance: { type: Number },
          totalDistance: { type: Number },
          ip: { type: String },
          motion: { type: Boolean },
          hours: { type: Number },
        },
        deviceId: { type: Number },
        type: { type: String },
        protocol: { type: String },
        serverTime: { type: Date },
        deviceTime: { type: Date },
        fixTime: { type: Date },
        outdated: { type: Boolean },
        valid: { type: Boolean },
        latitude: { type: Number },
        longitude: { type: Number },
        altitude: { type: Number },
        speed: { type: Number },
        course: { type: Number },
        address: { type: String },
        accuracy: { type: Number },
        network: { type: Schema.Types.Mixed },
      },
    ],
    puntos_recoleccion: [
      {
        lat: { type: Number },
        lng: { type: Number },
        timestamp: { type: Date },
        speed: { type: Number },
        destacado: { type: Boolean },
        retorno: { type: Boolean },
      },
    ],
    capacidad_retorno: [
      {
        label: { type: String, require: true },
        value: { type: String, require: true },
      },
      { _id: false },
    ], // Nuevo campo de capacidad
    view: { type: Boolean, default: true, description: "View status" },
    view_id: {
      type: Schema.Types.ObjectId,
      ref: "user",
      description: "Viewed by",
    },
    view_date: { type: Date, description: "View date" },
  },
  {
    timestamps: true,
  }
);

// Middleware para establecer la propiedad dateOnly antes de guardar
RecolectoresSchema.pre("save", function (next) {
  const date = new Date(this.createdAt);
  this.dateOnly = `${date.getFullYear()}-${
    date.getMonth() + 1
  }-${date.getDate()}`;

  // Filtrar los puntos de recolección que tienen `retorno: true`
  const puntosConRetorno = this.puntos_recoleccion.filter(
    (punto) => punto.retorno === true
  );

  // Si `capacidad_retorno` tiene más elementos que `puntosConRetorno`, ajustarlo
  if (this.capacidad_retorno.length > puntosConRetorno.length) {
    this.capacidad_retorno = this.capacidad_retorno.slice(
      0,
      puntosConRetorno.length
    );
  }
  if (this.view == false) {
    this.view_date = new Date();
  } else {
    this.view_date = null;
  }

  // Si `capacidad_retorno` tiene menos elementos que `puntosConRetorno`, rellenarlo con valores por defecto (ej. "vacío")
  while (this.capacidad_retorno.length < puntosConRetorno.length) {
    this.capacidad_retorno.push("vacío"); // Puedes cambiar "vacío" a otro valor predeterminado si lo deseas
  }

  next();
});

RecolectoresSchema.index({ dateOnly: 1, deviceId: 1 }, { unique: true });
RecolectoresSchema.index({ dateOnly: 1, funcionario: 1 }, { unique: true });

RecolectoresSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};
RecolectoresSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};

const RequestSchema = new Schema(
  {
    dni: { type: String, required: true, description: "DNI of the requester" }, // Consider renaming to idNumber or similar
    name: {
      type: String,
      required: true,
      description: "Name of the requester",
    },
    phone: {
      type: String,
      required: true,
      description: "Phone number of the requester",
    },
    address: {
      type: String,
      required: true,
      description: "Address of the requester",
    },
    email: {
      type: String,
      required: true,
      description: "Email of the requester",
    },
    issueDescription: {
      type: String,
      required: true,
      description: "Description of the issue",
    },
    assignees: {
      type: Schema.Types.ObjectId,
      ref: "user",
      required: true,
      description: "Assignees for the request",
    },
    foto: {
      type: [{ type: String }],
      description: "Photo evidence related to the request",
    },
    evidencia: {
      type: [{ type: String }],
      description: "Additional evidence related to the request",
    },
  },
  {
    timestamps: true,
  }
);

//control de acceso a la ruta
RequestSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ]; // método 'post' libre
  return protectedMethods.includes(method);
};

//control de creación de ruta
RequestSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
// Exportar los esquemas
const ExternoSchema = new Schema({
  name: { type: String, required: true },
  dni: { type: String, required: true, unique:true},
  phone: { type: String, required: true },
  address: { type: String, required: true },
},
{
  timestamps: true,
});
//control de acceso a la ruta
ExternoSchema.statics.isProtected = function (method) {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ]; // método 'post' libre
  return protectedMethods.includes(method);
};

//control de creación de ruta
ExternoSchema.statics.isAutogenerated = function (method) {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};

export const models = {
  Externo: mongoose.model("externo", ExternoSchema),
  Permiso: mongoose.model("permisos", permisosSchema),
  Usuario: mongoose.model("usuario", UsuarioSchema),
  Ficha_sectorial: mongoose.model("ficha_sectorial", FichaSectorialSchema),
  Incidentes_denuncia: mongoose.model(
    "incidentes_denuncia",
    IncidentesDenunciaSchema
  ),
  Categoria: mongoose.model("categoria", CategoriaSchema),
  Subcategoria: mongoose.model("subcategoria", SubcategoriaSchema),
  Encargado_categoria: mongoose.model(
    "encargado_categoria",
    EncargadoCategoriaSchema
  ),
  Rol_user: mongoose.model("rol_user", RolUserSchema),
  Estado_incidente: mongoose.model("estado_incidente", EstadoIncidenteSchema),
  Estado_actividad_proyecto: mongoose.model(
    "estado_actividad_proyecto",
    EstadoActividadProyectoSchema
  ),
  Actividad_proyecto: mongoose.model(
    "actividad_proyecto",
    ActividadProyectoSchema
  ),
  Direccion_geo: mongoose.model("direccion_geo", DireccionGeoSchema),
  Recolector: mongoose.model("recolector", RecolectoresSchema),
  Request: mongoose.model("Request", RequestSchema),
};
export const SchemaModelOld = {
  permisosSchema,
  UsuarioSchema,
  FichaSectorialSchema,
  IncidentesDenunciaSchema,
  CategoriaSchema,
  SubcategoriaSchema,
  EncargadoCategoriaSchema,
  EstadoActividadProyectoSchema,
  RolUserSchema,
  ActividadProyectoSchema,
  DireccionGeoSchema,
  RecolectoresSchema,
  RequestSchema,
};
